name: Beego

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        GOPROXY: "https://goproxy.cn"
        GO111MODULE: "on"
      run: go build -v .

    - name: Test
      run: go test -v .
